### ISSUE TITLE
Migration to elm 0.17

### ISSUE THREAD

**Issue by kgashok** [twopoint718/elmchat#5]
It would be great if this was migrated. Any plans?

**Comment by twopoint718** [comment]
@kgashok Yes, I do intend to to it, just been busy. @specious was nice enough to send me a PR with upgrades for 0.16. Thanks a ton!

I'll make time for it this week. Thanks for the heads-up!

**Comment by hakonrossebo** [comment]
I've referenced this project here - https://github.com/hakonrossebo/migrating-existing-projects-to-current-version-of-elm/blob/master/README.md - if you want other people to contribute with a PR to 0.17. Since the elm-lang.org also reference to this article - is it possible to somehow update the article when the project has been upgraded?

**Comment by twopoint718** [comment]
@hakonrossebo I didn't realize that it was linked from elm-lang.org! Good to know. This article is hosted at my previous employer, but I should be able to get it updated. Thanks for the heads-up.

**Comment by twopoint718** [comment]
@hakonrossebo @kgashok @specious I've updated the code to 0.17 as of commit 88bb55deb20d31743da84dd601b2a8237f7f8909. Thanks for the help! I'm going to close this issue unless you notice any errors. Thanks again.

**Comment by hakonrossebo** [comment]
Thanks :)
